import createClient from 'openapi-fetch'
import type { paths } from './schema'

/**
 * Typed API client. Paths, params and response bodies are checked against the backend's
 * OpenAPI spec (src/api/schema.d.ts, generated by scripts/gen-api.sh).
 *
 * Requests go to the same origin: in development Vite proxies /api to FastAPI, so the
 * session cookie is first-party and no CORS is involved.
 */
export const api = createClient<paths>({
  baseUrl: window.location.origin,
  // Look fetch up at call time (not import time) so tests can stub it.
  fetch: (request) => globalThis.fetch(request),
})

export class ApiError extends Error {
  readonly status: number

  constructor(status: number, message: string) {
    super(message)
    this.name = 'ApiError'
    this.status = status
  }
}

type ApiResult<T> = { data?: T; error?: unknown; response: Response }

/** Returns the response data, or throws an ApiError (so TanStack Query sees a failure). */
export async function unwrap<T>(request: Promise<ApiResult<T>>): Promise<T> {
  const { data, error, response } = await request
  if (error !== undefined || !response.ok) {
    throw new ApiError(response.status, errorMessage(error) ?? response.statusText)
  }
  return data as T
}

function errorMessage(error: unknown): string | undefined {
  // FastAPI errors look like {"detail": "..."} or {"detail": [{"msg": "..."}]}.
  if (error && typeof error === 'object' && 'detail' in error) {
    const { detail } = error as { detail: unknown }
    if (typeof detail === 'string') return detail
    if (Array.isArray(detail)) return detail.map((d: { msg?: string }) => d.msg).join('; ')
  }
  return undefined
}
