/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/config': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Auth Config
     * @description Public settings the frontend needs to render the sign-in button.
     */
    get: operations['auth_config']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/google': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Login With Google */
    post: operations['login_with_google']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Logout */
    post: operations['logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Me */
    get: operations['me']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/exercises': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Exercises */
    get: operations['list_exercises']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/exercises/filters': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Exercise Filters */
    get: operations['exercise_filters']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/exercises/{exercise_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Exercise */
    get: operations['get_exercise']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations['health']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** AuthConfig */
    AuthConfig: {
      /** Google Client Id */
      google_client_id: string
    }
    /** ExerciseDetail */
    ExerciseDetail: {
      /** Id */
      id: number
      /** Slug */
      slug: string
      /** Name */
      name: string
      /** Equipment */
      equipment: string | null
      /** Category */
      category: string | null
      /** Level */
      level: string | null
      /** Mechanic */
      mechanic: string | null
      /** Force */
      force: string | null
      /** Is Custom */
      is_custom: boolean
      /** Primary Muscles */
      primary_muscles: string[]
      /** Secondary Muscles */
      secondary_muscles: string[]
      /** Image Urls */
      image_urls: string[]
      /** Instructions */
      instructions: string[]
    }
    /**
     * ExerciseFilters
     * @description Values available for the filter chips in the exercise library.
     */
    ExerciseFilters: {
      /** Muscles */
      muscles: string[]
      /** Equipment */
      equipment: string[]
      /** Categories */
      categories: string[]
    }
    /** ExercisePage */
    ExercisePage: {
      /** Items */
      items: components['schemas']['ExerciseSummary'][]
      /** Total */
      total: number
      /** Limit */
      limit: number
      /** Offset */
      offset: number
    }
    /** ExerciseSummary */
    ExerciseSummary: {
      /** Id */
      id: number
      /** Slug */
      slug: string
      /** Name */
      name: string
      /** Equipment */
      equipment: string | null
      /** Category */
      category: string | null
      /** Level */
      level: string | null
      /** Mechanic */
      mechanic: string | null
      /** Force */
      force: string | null
      /** Is Custom */
      is_custom: boolean
      /** Primary Muscles */
      primary_muscles: string[]
      /** Secondary Muscles */
      secondary_muscles: string[]
      /** Image Urls */
      image_urls: string[]
    }
    /** GoogleLogin */
    GoogleLogin: {
      /** Credential */
      credential: string
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** UserOut */
    UserOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Email */
      email: string
      /** Name */
      name: string | null
      /** Avatar Url */
      avatar_url: string | null
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type AuthConfig = components['schemas']['AuthConfig']
export type ExerciseDetail = components['schemas']['ExerciseDetail']
export type ExerciseFilters = components['schemas']['ExerciseFilters']
export type ExercisePage = components['schemas']['ExercisePage']
export type ExerciseSummary = components['schemas']['ExerciseSummary']
export type GoogleLogin = components['schemas']['GoogleLogin']
export type HttpValidationError = components['schemas']['HTTPValidationError']
export type UserOut = components['schemas']['UserOut']
export type ValidationError = components['schemas']['ValidationError']
export type $defs = Record<string, never>
export interface operations {
  auth_config: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuthConfig']
        }
      }
    }
  }
  login_with_google: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['GoogleLogin']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  me: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_exercises: {
    parameters: {
      query?: {
        /** @description Search words in the name */
        q?: string | null
        /** @description Primary muscle, e.g. 'chest' */
        muscle?: string | null
        equipment?: string | null
        category?: string | null
        limit?: number
        offset?: number
      }
      header?: never
      path?: never
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExercisePage']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  exercise_filters: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExerciseFilters']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_exercise: {
    parameters: {
      query?: never
      header?: never
      path: {
        exercise_id: number
      }
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExerciseDetail']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  health: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: string
          }
        }
      }
    }
  }
}
