/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/config': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Auth Config
     * @description Public settings the frontend needs to render the sign-in button.
     */
    get: operations['auth_config']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/google': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Login With Google */
    post: operations['login_with_google']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Logout */
    post: operations['logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Me */
    get: operations['me']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Update Me */
    patch: operations['update_me']
    trace?: never
  }
  '/api/exercises': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Exercises */
    get: operations['list_exercises']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/exercises/filters': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Exercise Filters */
    get: operations['exercise_filters']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/exercises/{exercise_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Exercise */
    get: operations['get_exercise']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/workouts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Workouts */
    get: operations['list_workouts']
    put?: never
    /** Start Workout */
    post: operations['start_workout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/workouts/active': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Active Workout */
    get: operations['active_workout']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/workouts/{workout_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Workout */
    get: operations['get_workout']
    put?: never
    post?: never
    /** Delete Workout */
    delete: operations['delete_workout']
    options?: never
    head?: never
    /** Update Workout */
    patch: operations['update_workout']
    trace?: never
  }
  '/api/workouts/{workout_id}/finish': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Finish Workout */
    post: operations['finish_workout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/workouts/{workout_id}/exercises': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Add Workout Exercise */
    post: operations['add_workout_exercise']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/workouts/{workout_id}/exercises/order': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Reorder Workout Exercises */
    put: operations['reorder_workout_exercises']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/workout-exercises/{workout_exercise_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Remove Workout Exercise */
    delete: operations['remove_workout_exercise']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/sets/{set_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Save Set
     * @description Create or replace a set. The client picks the id, so retries are harmless.
     */
    put: operations['save_set']
    post?: never
    /**
     * Delete Set
     * @description Idempotent: deleting a set that's already gone also succeeds.
     */
    delete: operations['delete_set']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/exercises/{exercise_id}/history': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Exercise History
     * @description Your previous (finished) sessions of an exercise, newest first.
     */
    get: operations['exercise_history']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/stats/overview': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Stats Overview
     * @description Every exercise you've done, most recently trained first.
     */
    get: operations['stats_overview']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/stats/exercises/{exercise_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Exercise Stats */
    get: operations['exercise_stats']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/routine': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Routine */
    get: operations['get_routine']
    /**
     * Save Routine
     * @description Replace the routine. Days sent with their existing id keep it, so workouts stay
     *     linked to them (and the rotation keeps its place); days left out are deleted.
     */
    put: operations['save_routine']
    post?: never
    /** Delete Routine */
    delete: operations['delete_routine']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/routine/from-history': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create Routine From History
     * @description Turn your named workouts (e.g. Day1/Day2/Day3) into your routine.
     */
    post: operations['create_routine_from_history']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/exercise-preferences': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Exercise Preferences
     * @description All your per-exercise settings (only the exercises you changed something for).
     */
    get: operations['list_exercise_preferences']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/exercise-preferences/{exercise_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Save Exercise Preference */
    put: operations['save_exercise_preference']
    post?: never
    /**
     * Reset Exercise Preference
     * @description Back to the automatic rest time. Idempotent.
     */
    delete: operations['reset_exercise_preference']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations['health']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** AuthConfig */
    AuthConfig: {
      /** Google Client Id */
      google_client_id: string
    }
    /** ExerciseDetail */
    ExerciseDetail: {
      /** Id */
      id: number
      /** Slug */
      slug: string
      /** Name */
      name: string
      /** Equipment */
      equipment: string | null
      /** Category */
      category: string | null
      /** Level */
      level: string | null
      /** Mechanic */
      mechanic: string | null
      /** Force */
      force: string | null
      /** Is Custom */
      is_custom: boolean
      /** Primary Muscles */
      primary_muscles: string[]
      /** Secondary Muscles */
      secondary_muscles: string[]
      /** Image Urls */
      image_urls: string[]
      /** Instructions */
      instructions: string[]
    }
    /**
     * ExerciseFilters
     * @description Values available for the filter chips in the exercise library.
     */
    ExerciseFilters: {
      /** Muscles */
      muscles: string[]
      /** Equipment */
      equipment: string[]
      /** Categories */
      categories: string[]
    }
    /**
     * ExerciseOrder
     * @description All of the workout's exercise ids, in the new order.
     */
    ExerciseOrder: {
      /** Workout Exercise Ids */
      workout_exercise_ids: string[]
    }
    /** ExerciseOverviewOut */
    ExerciseOverviewOut: {
      exercise: components['schemas']['ExerciseSummary']
      /** Sets Logged */
      sets_logged: number
      /**
       * Last Performed On
       * Format: date
       */
      last_performed_on: string
      /** Last Top Weight Kg */
      last_top_weight_kg: number
      /** Max Weight Kg */
      max_weight_kg: number
      /** Best E1Rm Kg */
      best_e1rm_kg: number
      /** Total Volume Kg */
      total_volume_kg: number
    }
    /** ExercisePage */
    ExercisePage: {
      /** Items */
      items: components['schemas']['ExerciseSummary'][]
      /** Total */
      total: number
      /** Limit */
      limit: number
      /** Offset */
      offset: number
    }
    /** ExercisePreferenceIn */
    ExercisePreferenceIn: {
      /** Rest Seconds */
      rest_seconds: number
    }
    /** ExercisePreferenceOut */
    ExercisePreferenceOut: {
      /** Exercise Id */
      exercise_id: number
      /** Rest Seconds */
      rest_seconds: number
    }
    /**
     * ExerciseSession
     * @description One past workout's sets for a single exercise (for "last time" hints).
     */
    ExerciseSession: {
      /**
       * Workout Id
       * Format: uuid
       */
      workout_id: string
      /** Workout Name */
      workout_name: string | null
      /**
       * Performed On
       * Format: date
       */
      performed_on: string
      /** Sets */
      sets: components['schemas']['SetOut'][]
    }
    /** ExerciseStats */
    ExerciseStats: {
      records: components['schemas']['RecordsOut'] | null
      /** Sessions */
      sessions: components['schemas']['SessionPoint'][]
    }
    /** ExerciseSummary */
    ExerciseSummary: {
      /** Id */
      id: number
      /** Slug */
      slug: string
      /** Name */
      name: string
      /** Equipment */
      equipment: string | null
      /** Category */
      category: string | null
      /** Level */
      level: string | null
      /** Mechanic */
      mechanic: string | null
      /** Force */
      force: string | null
      /** Is Custom */
      is_custom: boolean
      /** Primary Muscles */
      primary_muscles: string[]
      /** Secondary Muscles */
      secondary_muscles: string[]
      /** Image Urls */
      image_urls: string[]
    }
    /** GoogleLogin */
    GoogleLogin: {
      /** Credential */
      credential: string
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /**
     * MeUpdate
     * @description Only the fields that are sent are changed.
     */
    MeUpdate: {
      /** Setup Completed */
      setup_completed?: boolean | null
      /** Rest Timer Enabled */
      rest_timer_enabled?: boolean | null
      /** Default Rest Seconds */
      default_rest_seconds?: number | null
    }
    /** RecordsOut */
    RecordsOut: {
      heaviest: components['schemas']['SetRecordOut']
      best_e1rm: components['schemas']['SetRecordOut']
      /** Best E1Rm Kg */
      best_e1rm_kg: number
      /** Best Session Volume Kg */
      best_session_volume_kg: number
      /**
       * Best Session Volume On
       * Format: date
       */
      best_session_volume_on: string
      /** Rep Records */
      rep_records: components['schemas']['SetRecordOut'][]
    }
    /** RoutineDayIn */
    RoutineDayIn: {
      /** Id */
      id?: string | null
      /** Name */
      name: string
      /**
       * Exercises
       * @default []
       */
      exercises: components['schemas']['RoutineExerciseIn'][]
    }
    /** RoutineDayOut */
    RoutineDayOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Position */
      position: number
      /** Name */
      name: string
      /** Exercises */
      exercises: components['schemas']['RoutineExerciseOut'][]
    }
    /** RoutineExerciseIn */
    RoutineExerciseIn: {
      /** Exercise Id */
      exercise_id: number
      /**
       * Sets
       * @default 3
       */
      sets: number
    }
    /** RoutineExerciseOut */
    RoutineExerciseOut: {
      exercise: components['schemas']['ExerciseSummary']
      /** Sets */
      sets: number
    }
    /**
     * RoutineIn
     * @description The whole routine; days are in rotation order.
     */
    RoutineIn: {
      /** Days */
      days: components['schemas']['RoutineDayIn'][]
    }
    /** RoutineOut */
    RoutineOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Days */
      days: components['schemas']['RoutineDayOut'][]
      /** Next Day Id */
      next_day_id: string | null
    }
    /** SessionPoint */
    SessionPoint: {
      /**
       * Workout Id
       * Format: uuid
       */
      workout_id: string
      /**
       * Performed On
       * Format: date
       */
      performed_on: string
      /** Top Weight Kg */
      top_weight_kg: number
      /** Top Weight Reps */
      top_weight_reps: number
      /** Best E1Rm Kg */
      best_e1rm_kg: number
      /** Volume Kg */
      volume_kg: number
      /** Set Count */
      set_count: number
    }
    /**
     * SetIn
     * @description Full state of a set (PUT semantics: fields left out are cleared).
     */
    SetIn: {
      /**
       * Workout Exercise Id
       * Format: uuid
       */
      workout_exercise_id: string
      /** Position */
      position: number
      /** Weight Kg */
      weight_kg?: number | string | null
      /** Reps */
      reps?: number | null
      /** Rpe */
      rpe?: number | string | null
      /**
       * Is Warmup
       * @default false
       */
      is_warmup: boolean
      /** Notes */
      notes?: string | null
      /** Completed At */
      completed_at?: string | null
    }
    /** SetOut */
    SetOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Workout Exercise Id
       * Format: uuid
       */
      workout_exercise_id: string
      /** Position */
      position: number
      /** Weight Kg */
      weight_kg: number | null
      /** Reps */
      reps: number | null
      /** Rpe */
      rpe: number | null
      /** Is Warmup */
      is_warmup: boolean
      /** Notes */
      notes: string | null
      /** Completed At */
      completed_at: string | null
    }
    /** SetRecordOut */
    SetRecordOut: {
      /** Weight Kg */
      weight_kg: number
      /** Reps */
      reps: number
      /**
       * Performed On
       * Format: date
       */
      performed_on: string
    }
    /** UserOut */
    UserOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Email */
      email: string
      /** Name */
      name: string | null
      /** Avatar Url */
      avatar_url: string | null
      /** Setup Completed At */
      setup_completed_at: string | null
      /** Rest Timer Enabled */
      rest_timer_enabled: boolean
      /** Default Rest Seconds */
      default_rest_seconds: number
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
    /** WorkoutCreate */
    WorkoutCreate: {
      /** Id */
      id?: string | null
      /** Name */
      name?: string | null
      /** Performed On */
      performed_on?: string | null
      /** Started At */
      started_at?: string | null
      /** Routine Day Id */
      routine_day_id?: string | null
    }
    /** WorkoutDetail */
    WorkoutDetail: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Name */
      name: string | null
      /** Routine Day Id */
      routine_day_id: string | null
      /**
       * Performed On
       * Format: date
       */
      performed_on: string
      status: components['schemas']['WorkoutStatus']
      /** Started At */
      started_at: string | null
      /** Ended At */
      ended_at: string | null
      /** Notes */
      notes: string | null
      /** Exercises */
      exercises: components['schemas']['WorkoutExerciseOut'][]
    }
    /** WorkoutExerciseIn */
    WorkoutExerciseIn: {
      /** Id */
      id?: string | null
      /** Exercise Id */
      exercise_id: number
      /** Notes */
      notes?: string | null
    }
    /** WorkoutExerciseOut */
    WorkoutExerciseOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Position */
      position: number
      /** Notes */
      notes: string | null
      exercise: components['schemas']['ExerciseSummary']
      /** Sets */
      sets: components['schemas']['SetOut'][]
    }
    /** WorkoutFinish */
    WorkoutFinish: {
      /** Ended At */
      ended_at?: string | null
    }
    /** WorkoutPage */
    WorkoutPage: {
      /** Items */
      items: components['schemas']['WorkoutSummary'][]
      /** Total */
      total: number
      /** Limit */
      limit: number
      /** Offset */
      offset: number
    }
    /**
     * WorkoutStatus
     * @enum {string}
     */
    WorkoutStatus: 'in_progress' | 'completed'
    /** WorkoutSummary */
    WorkoutSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Name */
      name: string | null
      /** Routine Day Id */
      routine_day_id: string | null
      /**
       * Performed On
       * Format: date
       */
      performed_on: string
      status: components['schemas']['WorkoutStatus']
      /** Started At */
      started_at: string | null
      /** Ended At */
      ended_at: string | null
      /** Exercise Names */
      exercise_names: string[]
      /** Set Count */
      set_count: number
      /** Volume Kg */
      volume_kg: number
    }
    /**
     * WorkoutUpdate
     * @description Only the fields that are sent are changed.
     */
    WorkoutUpdate: {
      /** Name */
      name?: string | null
      /** Notes */
      notes?: string | null
      /** Performed On */
      performed_on?: string | null
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type AuthConfig = components['schemas']['AuthConfig']
export type ExerciseDetail = components['schemas']['ExerciseDetail']
export type ExerciseFilters = components['schemas']['ExerciseFilters']
export type ExerciseOrder = components['schemas']['ExerciseOrder']
export type ExerciseOverviewOut = components['schemas']['ExerciseOverviewOut']
export type ExercisePage = components['schemas']['ExercisePage']
export type ExercisePreferenceIn = components['schemas']['ExercisePreferenceIn']
export type ExercisePreferenceOut = components['schemas']['ExercisePreferenceOut']
export type ExerciseSession = components['schemas']['ExerciseSession']
export type ExerciseStats = components['schemas']['ExerciseStats']
export type ExerciseSummary = components['schemas']['ExerciseSummary']
export type GoogleLogin = components['schemas']['GoogleLogin']
export type HttpValidationError = components['schemas']['HTTPValidationError']
export type MeUpdate = components['schemas']['MeUpdate']
export type RecordsOut = components['schemas']['RecordsOut']
export type RoutineDayIn = components['schemas']['RoutineDayIn']
export type RoutineDayOut = components['schemas']['RoutineDayOut']
export type RoutineExerciseIn = components['schemas']['RoutineExerciseIn']
export type RoutineExerciseOut = components['schemas']['RoutineExerciseOut']
export type RoutineIn = components['schemas']['RoutineIn']
export type RoutineOut = components['schemas']['RoutineOut']
export type SessionPoint = components['schemas']['SessionPoint']
export type SetIn = components['schemas']['SetIn']
export type SetOut = components['schemas']['SetOut']
export type SetRecordOut = components['schemas']['SetRecordOut']
export type UserOut = components['schemas']['UserOut']
export type ValidationError = components['schemas']['ValidationError']
export type WorkoutCreate = components['schemas']['WorkoutCreate']
export type WorkoutDetail = components['schemas']['WorkoutDetail']
export type WorkoutExerciseIn = components['schemas']['WorkoutExerciseIn']
export type WorkoutExerciseOut = components['schemas']['WorkoutExerciseOut']
export type WorkoutFinish = components['schemas']['WorkoutFinish']
export type WorkoutPage = components['schemas']['WorkoutPage']
export type WorkoutStatus = components['schemas']['WorkoutStatus']
export type WorkoutSummary = components['schemas']['WorkoutSummary']
export type WorkoutUpdate = components['schemas']['WorkoutUpdate']
export type $defs = Record<string, never>
export interface operations {
  auth_config: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuthConfig']
        }
      }
    }
  }
  login_with_google: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['GoogleLogin']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  me: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_me: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MeUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_exercises: {
    parameters: {
      query?: {
        /** @description Search words in the name */
        q?: string | null
        /** @description Primary muscle, e.g. 'chest' */
        muscle?: string | null
        equipment?: string | null
        category?: string | null
        limit?: number
        offset?: number
      }
      header?: never
      path?: never
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExercisePage']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  exercise_filters: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExerciseFilters']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_exercise: {
    parameters: {
      query?: never
      header?: never
      path: {
        exercise_id: number
      }
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExerciseDetail']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_workouts: {
    parameters: {
      query?: {
        limit?: number
        offset?: number
        /** @description Inclusive, e.g. 2026-09-01 */
        performed_from?: string | null
        /** @description Inclusive, e.g. 2026-09-30 */
        performed_to?: string | null
      }
      header?: never
      path?: never
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkoutPage']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  start_workout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['WorkoutCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkoutDetail']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  active_workout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkoutDetail'] | null
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_workout: {
    parameters: {
      query?: never
      header?: never
      path: {
        workout_id: string
      }
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkoutDetail']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_workout: {
    parameters: {
      query?: never
      header?: never
      path: {
        workout_id: string
      }
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_workout: {
    parameters: {
      query?: never
      header?: never
      path: {
        workout_id: string
      }
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['WorkoutUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkoutDetail']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  finish_workout: {
    parameters: {
      query?: never
      header?: never
      path: {
        workout_id: string
      }
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['WorkoutFinish']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkoutDetail']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  add_workout_exercise: {
    parameters: {
      query?: never
      header?: never
      path: {
        workout_id: string
      }
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['WorkoutExerciseIn']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkoutDetail']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  reorder_workout_exercises: {
    parameters: {
      query?: never
      header?: never
      path: {
        workout_id: string
      }
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ExerciseOrder']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkoutDetail']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  remove_workout_exercise: {
    parameters: {
      query?: never
      header?: never
      path: {
        workout_exercise_id: string
      }
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkoutDetail']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  save_set: {
    parameters: {
      query?: never
      header?: never
      path: {
        set_id: string
      }
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SetIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SetOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_set: {
    parameters: {
      query?: never
      header?: never
      path: {
        set_id: string
      }
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  exercise_history: {
    parameters: {
      query?: {
        limit?: number
      }
      header?: never
      path: {
        exercise_id: number
      }
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExerciseSession'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  stats_overview: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExerciseOverviewOut'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  exercise_stats: {
    parameters: {
      query?: never
      header?: never
      path: {
        exercise_id: number
      }
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExerciseStats']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_routine: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RoutineOut'] | null
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  save_routine: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RoutineIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RoutineOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_routine: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_routine_from_history: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RoutineOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_exercise_preferences: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExercisePreferenceOut'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  save_exercise_preference: {
    parameters: {
      query?: never
      header?: never
      path: {
        exercise_id: number
      }
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ExercisePreferenceIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExercisePreferenceOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  reset_exercise_preference: {
    parameters: {
      query?: never
      header?: never
      path: {
        exercise_id: number
      }
      cookie?: {
        gt_session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  health: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: string
          }
        }
      }
    }
  }
}
