"""routines and setup

Revision ID: ecac339121a6
Revises: 21b193f8af3f
Create Date: 2026-09-25 15:20:33.209404

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ecac339121a6"
down_revision: str | Sequence[str] | None = "21b193f8af3f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "routines",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_routines_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_routines")),
        sa.UniqueConstraint("user_id", name=op.f("uq_routines_user_id")),
    )
    op.create_table(
        "routine_days",
        sa.Column("routine_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["routine_id"],
            ["routines.id"],
            name=op.f("fk_routine_days_routine_id_routines"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_routine_days")),
    )
    op.create_index(
        op.f("ix_routine_days_routine_id"), "routine_days", ["routine_id"], unique=False
    )
    op.create_table(
        "routine_exercises",
        sa.Column("day_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("sets", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint("sets BETWEEN 1 AND 20", name=op.f("ck_routine_exercises_sets_range")),
        sa.ForeignKeyConstraint(
            ["day_id"],
            ["routine_days.id"],
            name=op.f("fk_routine_exercises_day_id_routine_days"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
            name=op.f("fk_routine_exercises_exercise_id_exercises"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_routine_exercises")),
    )
    op.create_index(
        op.f("ix_routine_exercises_day_id"), "routine_exercises", ["day_id"], unique=False
    )
    op.create_index(
        op.f("ix_routine_exercises_exercise_id"), "routine_exercises", ["exercise_id"], unique=False
    )
    op.add_column(
        "users", sa.Column("setup_completed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("workouts", sa.Column("routine_day_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_workouts_routine_day_id"), "workouts", ["routine_day_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_workouts_routine_day_id_routine_days"),
        "workouts",
        "routine_days",
        ["routine_day_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_workouts_routine_day_id_routine_days"), "workouts", type_="foreignkey"
    )
    op.drop_index(op.f("ix_workouts_routine_day_id"), table_name="workouts")
    op.drop_column("workouts", "routine_day_id")
    op.drop_column("users", "setup_completed_at")
    op.drop_index(op.f("ix_routine_exercises_exercise_id"), table_name="routine_exercises")
    op.drop_index(op.f("ix_routine_exercises_day_id"), table_name="routine_exercises")
    op.drop_table("routine_exercises")
    op.drop_index(op.f("ix_routine_days_routine_id"), table_name="routine_days")
    op.drop_table("routine_days")
    op.drop_table("routines")
    # ### end Alembic commands ###
