"""initial schema

Revision ID: 21b193f8af3f
Revises:
Create Date: 2026-09-24 13:06:29.832843

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "21b193f8af3f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "muscles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_muscles")),
        sa.UniqueConstraint("name", name=op.f("uq_muscles_name")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("google_sub", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("avatar_url", sa.String(length=2048), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("google_sub", name=op.f("uq_users_google_sub")),
    )
    op.create_table(
        "exercises",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("equipment", sa.String(length=50), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("level", sa.String(length=20), nullable=True),
        sa.Column("mechanic", sa.String(length=20), nullable=True),
        sa.Column("force", sa.String(length=20), nullable=True),
        sa.Column("instructions", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("image_paths", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_exercises_owner_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercises")),
        sa.UniqueConstraint("slug", name=op.f("uq_exercises_slug")),
    )
    op.create_index(op.f("ix_exercises_owner_id"), "exercises", ["owner_id"], unique=False)
    op.create_index(
        "uq_exercises_owner_id_lower_name",
        "exercises",
        ["owner_id", sa.literal_column("lower(name)")],
        unique=True,
        postgresql_where=sa.text("owner_id IS NOT NULL"),
    )
    op.create_table(
        "workouts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("performed_on", sa.Date(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "in_progress",
                "completed",
                name="status",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("import_key", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_workouts_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workouts")),
        sa.UniqueConstraint("user_id", "import_key", name=op.f("uq_workouts_user_id_import_key")),
    )
    op.create_index(
        "ix_workouts_user_id_performed_on", "workouts", ["user_id", "performed_on"], unique=False
    )
    op.create_index(
        "uq_workouts_user_id_in_progress",
        "workouts",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'in_progress'"),
    )
    op.create_table(
        "exercise_muscles",
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("muscle_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "primary",
                "secondary",
                name="role",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
            name=op.f("fk_exercise_muscles_exercise_id_exercises"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["muscle_id"],
            ["muscles.id"],
            name=op.f("fk_exercise_muscles_muscle_id_muscles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("exercise_id", "muscle_id", name=op.f("pk_exercise_muscles")),
    )
    op.create_table(
        "workout_exercises",
        sa.Column("workout_id", sa.Uuid(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
            name=op.f("fk_workout_exercises_exercise_id_exercises"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workout_id"],
            ["workouts.id"],
            name=op.f("fk_workout_exercises_workout_id_workouts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workout_exercises")),
    )
    op.create_index(
        op.f("ix_workout_exercises_exercise_id"), "workout_exercises", ["exercise_id"], unique=False
    )
    op.create_index(
        op.f("ix_workout_exercises_workout_id"), "workout_exercises", ["workout_id"], unique=False
    )
    op.create_table(
        "sets",
        sa.Column("workout_exercise_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("weight_kg", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("reps", sa.Integer(), nullable=True),
        sa.Column("rpe", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column("is_warmup", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("reps >= 0", name=op.f("ck_sets_reps_non_negative")),
        sa.CheckConstraint("rpe BETWEEN 1 AND 10", name=op.f("ck_sets_rpe_range")),
        sa.CheckConstraint("weight_kg >= 0", name=op.f("ck_sets_weight_kg_non_negative")),
        sa.ForeignKeyConstraint(
            ["workout_exercise_id"],
            ["workout_exercises.id"],
            name=op.f("fk_sets_workout_exercise_id_workout_exercises"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sets")),
    )
    op.create_index(
        op.f("ix_sets_workout_exercise_id"), "sets", ["workout_exercise_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sets_workout_exercise_id"), table_name="sets")
    op.drop_table("sets")
    op.drop_index(op.f("ix_workout_exercises_workout_id"), table_name="workout_exercises")
    op.drop_index(op.f("ix_workout_exercises_exercise_id"), table_name="workout_exercises")
    op.drop_table("workout_exercises")
    op.drop_table("exercise_muscles")
    op.drop_index(
        "uq_workouts_user_id_in_progress",
        table_name="workouts",
        postgresql_where=sa.text("status = 'in_progress'"),
    )
    op.drop_index("ix_workouts_user_id_performed_on", table_name="workouts")
    op.drop_table("workouts")
    op.drop_index(
        "uq_exercises_owner_id_lower_name",
        table_name="exercises",
        postgresql_where=sa.text("owner_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_exercises_owner_id"), table_name="exercises")
    op.drop_table("exercises")
    op.drop_table("users")
    op.drop_table("muscles")
    # ### end Alembic commands ###
