"""exercise fks safe for cascades

Revision ID: 122c5d26a589
Revises: ecac339121a6
Create Date: 2026-09-25 15:44:42.943382

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "122c5d26a589"
down_revision: str | Sequence[str] | None = "ecac339121a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_routine_exercises_exercise_id_exercises"), "routine_exercises", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_routine_exercises_exercise_id_exercises"),
        "routine_exercises",
        "exercises",
        ["exercise_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_workout_exercises_exercise_id_exercises"), "workout_exercises", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_workout_exercises_exercise_id_exercises"),
        "workout_exercises",
        "exercises",
        ["exercise_id"],
        ["id"],
        initially="DEFERRED",
        deferrable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_workout_exercises_exercise_id_exercises"), "workout_exercises", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_workout_exercises_exercise_id_exercises"),
        "workout_exercises",
        "exercises",
        ["exercise_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_constraint(
        op.f("fk_routine_exercises_exercise_id_exercises"), "routine_exercises", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_routine_exercises_exercise_id_exercises"),
        "routine_exercises",
        "exercises",
        ["exercise_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###
