"""rest preferences

Revision ID: b99a33a8ab69
Revises: 122c5d26a589
Create Date: 2026-09-26 08:22:48.930004

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b99a33a8ab69"
down_revision: str | Sequence[str] | None = "122c5d26a589"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercise_preferences",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("rest_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "rest_seconds BETWEEN 0 AND 900", name=op.f("ck_exercise_preferences_rest_range")
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
            name=op.f("fk_exercise_preferences_exercise_id_exercises"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_exercise_preferences_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "exercise_id", name=op.f("pk_exercise_preferences")),
    )
    op.add_column(
        "users",
        sa.Column("rest_timer_enabled", sa.Boolean(), server_default="true", nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("default_rest_seconds", sa.Integer(), server_default="90", nullable=False),
    )
    # Not detected by autogenerate (check constraint on an existing table).
    op.create_check_constraint(
        op.f("ck_users_default_rest_range"), "users", "default_rest_seconds BETWEEN 15 AND 600"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_users_default_rest_range"), "users", type_="check")
    op.drop_column("users", "default_rest_seconds")
    op.drop_column("users", "rest_timer_enabled")
    op.drop_table("exercise_preferences")
    # ### end Alembic commands ###
